version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - '9511:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  home:
    image: registry.cn-shanghai.aliyuncs.com/nonocast/todolist365-app-home:latest
    labels:
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'